<?php require_once($_SERVER['DOCUMENT_ROOT'].'/includes/inc.php'); ?>
<div class="flex flex-row-d-col-m gap-1">
    <div class="flex flex-col w-fa gap-1 border-soft item-bg box-shadow padding-1">
        <div class="flex flex-col gap-025">
            <div class="flex flex-row flex-align-c flex-justify-con-sb gap-05">
                <span class="text-primary bold">Termék létrehozása</span>
                <span class="flex flex-row primary-bg primary-bg-hover pointer border-soft-light padding-05 w-fc" id="add-product">Mentés</span>
            </div>
            <hr style="border: 1px solid var(--background);" class="w-100">
        </div>
        <div class="flex flex-col gap-1">
            <div class="flex flex-col gap-1">
                <div id="pd-st-ind-final">
                    <div class="flex flex-row-d-col-m flex-align-c flex-justify-con-sb border-soft border-secondary-dotted text-secondary background-bg padding-1">
                        <div class="flex flex-row-d-col-m flex-align-c gap-1">
                            <div class="flex flex-row flex-align-c gap-1 w-fa">
                                <div class="flex">
                                    <svg class="drop-shadow" width="36" height="36" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><rect opacity="0.3" x="2" y="2" width="20" height="20" rx="10" fill="currentColor"/><rect x="11" y="14" width="7" height="2" rx="1" transform="rotate(-90 11 14)" fill="currentColor"/><rect x="11" y="17" width="2" height="2" rx="1" transform="rotate(-90 11 17)" fill="currentColor"/></svg>
                                </div>
                                <div class="flex flex-col flex-align-c flex-justify-con-fs w-fa">
                                    <span class="bold w-100 small">A termék státusza nem lett beállítva.</span>
                                    <span class="text-warning small-med">A termék státuszának beállítása elengedhetetlen a termék publikálásához. Ezt a státusz-beállítást bármikor módosíthatja a <em>Termékek szerkesztése</em> menüpontban, vagy <span class="link bold pointer user-select-none" onclick="document.getElementById('tabs-general').click();">ide kattintva megváltoztathatja</span> most is.</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div id="en-er-rev" class="hidden"></div>
            <div id="pd-er-gen" class="hidden"></div>
            <div id="up-er-all" class="hidden"></div>
            <div id="up-sc-cn"></div>
            <div class="flex flex-col flex-align-c flex-justify-con-c gap-1 w-fa text-muted user-select-none">
                <svg class="drop-shadow" width="128" height="128" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path opacity="0.3" d="M18 10V20C18 20.6 18.4 21 19 21C19.6 21 20 20.6 20 20V10H18Z" fill="currentColor"/><path opacity="0.3" d="M11 10V17H6V10H4V20C4 20.6 4.4 21 5 21H12C12.6 21 13 20.6 13 20V10H11Z" fill="currentColor"/><path opacity="0.3" d="M10 10C10 11.1 9.1 12 8 12C6.9 12 6 11.1 6 10H10Z" fill="currentColor"/><path opacity="0.3" d="M18 10C18 11.1 17.1 12 16 12C14.9 12 14 11.1 14 10H18Z" fill="currentColor"/><path opacity="0.3" d="M14 4H10V10H14V4Z" fill="currentColor"/><path opacity="0.3" d="M17 4H20L22 10H18L17 4Z" fill="currentColor"/><path opacity="0.3" d="M7 4H4L2 10H6L7 4Z" fill="currentColor"/><path d="M6 10C6 11.1 5.1 12 4 12C2.9 12 2 11.1 2 10H6ZM10 10C10 11.1 10.9 12 12 12C13.1 12 14 11.1 14 10H10ZM18 10C18 11.1 18.9 12 20 12C21.1 12 22 11.1 22 10H18ZM19 2H5C4.4 2 4 2.4 4 3V4H20V3C20 2.4 19.6 2 19 2ZM12 17C12 16.4 11.6 16 11 16H6C5.4 16 5 16.4 5 17C5 17.6 5.4 18 6 18H11C11.6 18 12 17.6 12 17Z" fill="currentColor"/></svg>
                <span class="small-med w-60 text-align-c">Köszönjük, hogy bővíti webáruházunk kínálatát.</span>
            </div>
        </div>
    </div>
</div>
<script>
    function __displayApprEr (app) { 
        if (app > 0) { document.getElementById('pd-er-gen').classList.remove('hidden');
            document.getElementById('pd-er-gen').innerHTML = `
            <div class="flex flex-row-d-col-m flex-align-c flex-justify-con-sb border-soft border-warning-dotted warning-bg padding-1">
                <div class="flex flex-row-d-col-m flex-align-c gap-1">
                    <div class="flex flex-row flex-align-c gap-1 w-fa">
                        <div class="flex">
                            <svg class="drop-shadow" width="36" height="36" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path opacity="0.3" d="M19 22H5C4.4 22 4 21.6 4 21V3C4 2.4 4.4 2 5 2H14V4H6V20H18V8H20V21C20 21.6 19.6 22 19 22Z" fill="currentColor"/><path d="M15 8H20L14 2V7C14 7.6 14.4 8 15 8Z" fill="currentColor"/></svg>
                        </div>
                        <div class="flex flex-col flex-align-c flex-justify-con-fs w-fa">
                            <span class="bold w-100 small">Megközelítőleg ${app} db mezőt hagyott üresen.</span>
                            <span class="text-warning small-med">Úgy számoljuk, hogy Ön jelenleg nem töltött ki minden mezőt, amely szükséges a termék létrehozásához. Figyelem! Ez a számítás eltérhet a ténylegesen üresen hagyott mezők számától, ez csak egy megközelítő érték. Amennyiben úgy gondolja, hogy Ön kitöltött minden szükséges mezőt, hagyja figyelmen kívűl ezt az értesítést.</span>
                        </div>
                    </div>
                </div>
            </div>`;
        } else { document.getElementById('pd-er-gen').innerHTML = ``; document.getElementById('pd-er-gen').classList.add('hidden'); }
    }

    var apprInput = document.getElementsByClassName("prd-ch-fr-er"); var apprErr = 0; var apprCE = document.getElementsByClassName("prd-ch-fr-er-ce"); let emptyCE = 0; let emptyInp = 0;
    for (let i = 0; i < apprInput.length; i++) {
        if (apprInput[i].tagName !== 'TAGS') { if (apprInput[i].value.length < 1) { emptyInp++; }
            apprInput[i].addEventListener('input', () => { if (apprInput[i].value.length > 0) { emptyInp = emptyInp -1; __displayApprEr(emptyInp + emptyCE); } }, { once: true });
        }
    } for (let i = 0; i < apprCE.length; i++) { if (apprCE[i].getElementsByClassName('ql-editor')[0].textContent.length < 1) { emptyCE++; }
        apprCE[i].addEventListener('input', () => { if (apprCE[i].getElementsByClassName('ql-editor')[0].textContent.length > 0) { emptyCE = emptyCE -1; __displayApprEr(emptyCE + emptyInp); } }, { once: true });
    } __displayApprEr(emptyInp+emptyCE);

    $('#add-product').click(() => {
        var name = document.getElementById('product-name').value;
        var thumbnail = document.getElementById('product-thumbnail').files[0];
        var description = document.getElementById('prod-desc-editor').getElementsByClassName('ql-editor')[0].innerHTML;
        var status = document.getElementById('product-status').value;
        if (status == 3) { var schedule = document.getElementById('schedule-end').value; }
        var category = document.getElementById('product-category').value;
        var tags = document.getElementById('product-tags').value.split(',');
        var price = document.getElementById('product-price').value;
        var disc__ele = document.getElementsByName('product-discount');
        for (let i = 0; i < disc__ele.length; i++) { if (disc__ele[i].checked) { var discount = disc__ele[i].value; } }
        if (discount == 1) { var discount__range = document.getElementById('discount-range').value; var discount__start = document.getElementById('discount-start').value; var discount__end = document.getElementById('discount-end').value; }
        
        var code = document.getElementById('product-code').value;
        var quantity = document.getElementById('product-quantity').value;
        var quantity__wh = document.getElementById('product-quantity-wh').value;
        var quantity__unit = document.getElementById('product-quantity-unit').value;
        var backorder = document.getElementById('product-backorder').checked ? true : false;
        var color = document.getElementById('product-color').value.split(',');
        var material = document.getElementById('product-material').value.split(',');
        var style = document.getElementById('product-style').value;
        var brand = document.getElementById('product-brand').value;
        var model = document.getElementById('product-model').value;
        var physical = document.getElementById('product-physical').checked ? true : false;
        var refund = document.getElementById('product-refund').checked ? true : false;
        if (physical) { var weight = document.getElementById('product-weight').value; var weight__unit = document.getElementById('product-weight-unit').value; var width = document.getElementById('product-width').value; var height = document.getElementById('product-height').value; var length = document.getElementById('product-length').value; var dimension__unit = document.getElementById('product-dimension-unit').value; }
        var meta__title = document.getElementById('product-meta-title').value;
        var meta__description = document.getElementById('prod-meta-editor').getElementsByClassName('ql-editor')[0].textContent;
        var meta__keywords = document.getElementById('product-meta-keywords').value;

        var variations = document.getElementsByClassName('cst-var-con');
        if (variations.length > 0) { var variationArray = [];
            for (let i = 0; i < variations.length; i++) { var varname = variations[i].getElementsByClassName('cst-var-name')[0].value.replace(/,/g, ';'); var varvalue = variations[i].getElementsByClassName('cst-var-val')[0].value.replace(/,/g, ';');;
                if (varname.length > 0 && varvalue.length > 0) { var varitem = varname + ':' + varvalue; variationArray.push(varitem); }
            }
        }
        var review__allow = document.getElementById('product-review-stat').checked ? true : false; var review__auth = document.getElementById('product-review-auth').checked ? true : false;
        var review__vote = document.getElementById('product-review-vote').checked ? true : false; var review__privacy = document.getElementById('product-review-privacy').checked ? true : false;
        
        document.getElementById('up-sc-cn').innerHTML = `<div class="flex flex-row-d-col-m flex-align-c flex-justify-con-sb border-soft border-secondary-dotted text-secondary background-bg padding-1"><div class="flex flex-row-d-col-m flex-align-c gap-1"><div class="flex flex-row flex-align-c gap-1 w-fa"><div class="flex"><span class="text-muted"><svg class="wizard_input_loading" width="36" height="36" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M12.6 7C12 7 11.6 6.6 11.6 6V3C11.6 2.4 12 2 12.6 2C13.2 2 13.6 2.4 13.6 3V6C13.6 6.6 13.2 7 12.6 7ZM10 7.59998C10.5 7.29998 10.6 6.69995 10.4 6.19995L9 3.80005C8.7 3.30005 8.10001 3.20002 7.60001 3.40002C7.10001 3.70002 7.00001 4.30005 7.20001 4.80005L8.60001 7.19995C8.80001 7.49995 9.1 7.69995 9.5 7.69995C9.7 7.69995 9.9 7.69998 10 7.59998ZM8 9.30005C8.3 8.80005 8.10001 8.20002 7.60001 7.90002L5.5 6.69995C5 6.39995 4.40001 6.59998 4.10001 7.09998C3.80001 7.59998 4 8.2 4.5 8.5L6.60001 9.69995C6.80001 9.79995 6.90001 9.80005 7.10001 9.80005C7.50001 9.80005 7.9 9.70005 8 9.30005ZM7.20001 12C7.20001 11.4 6.80001 11 6.20001 11H4C3.4 11 3 11.4 3 12C3 12.6 3.4 13 4 13H6.20001C6.70001 13 7.20001 12.6 7.20001 12Z" fill="currentColor"/><path opacity="0.3" d="M17.4 5.5C17.4 6.1 17 6.5 16.4 6.5C15.8 6.5 15.4 6.1 15.4 5.5C15.4 4.9 15.8 4.5 16.4 4.5C17 4.5 17.4 5 17.4 5.5ZM5.80001 17.1L7.40001 16.1C7.90001 15.8 8.00001 15.2 7.80001 14.7C7.50001 14.2 6.90001 14.1 6.40001 14.3L4.80001 15.3C4.30001 15.6 4.20001 16.2 4.40001 16.7C4.60001 17 4.90001 17.2 5.30001 17.2C5.50001 17.3 5.60001 17.2 5.80001 17.1ZM8.40001 20.2C8.20001 20.2 8.10001 20.2 7.90001 20.1C7.40001 19.8 7.3 19.2 7.5 18.7L8.30001 17.3C8.60001 16.8 9.20002 16.7 9.70002 16.9C10.2 17.2 10.3 17.8 10.1 18.3L9.30001 19.7C9.10001 20 8.70001 20.2 8.40001 20.2ZM12.6 21.2C12 21.2 11.6 20.8 11.6 20.2V18.8C11.6 18.2 12 17.8 12.6 17.8C13.2 17.8 13.6 18.2 13.6 18.8V20.2C13.6 20.7 13.2 21.2 12.6 21.2ZM16.7 19.9C16.4 19.9 16 19.7 15.8 19.4L15.2 18.5C14.9 18 15.1 17.4 15.6 17.1C16.1 16.8 16.7 17 17 17.5L17.6 18.4C17.9 18.9 17.7 19.5 17.2 19.8C17 19.9 16.8 19.9 16.7 19.9ZM19.4 17C19.2 17 19.1 17 18.9 16.9L18.2 16.5C17.7 16.2 17.6 15.6 17.8 15.1C18.1 14.6 18.7 14.5 19.2 14.7L19.9 15.1C20.4 15.4 20.5 16 20.3 16.5C20.1 16.8 19.8 17 19.4 17ZM20.4 13H19.9C19.3 13 18.9 12.6 18.9 12C18.9 11.4 19.3 11 19.9 11H20.4C21 11 21.4 11.4 21.4 12C21.4 12.6 20.9 13 20.4 13ZM18.9 9.30005C18.6 9.30005 18.2 9.10005 18 8.80005C17.7 8.30005 17.9 7.70002 18.4 7.40002L18.6 7.30005C19.1 7.00005 19.7 7.19995 20 7.69995C20.3 8.19995 20.1 8.79998 19.6 9.09998L19.4 9.19995C19.3 9.19995 19.1 9.30005 18.9 9.30005Z" fill="currentColor"/></svg></span></div><div class="flex flex-col flex-align-c flex-justify-con-fs w-fa"><span class="bold w-100 small">Feldolgozás alatt.</span><span class="text-warning small-med">A termék felvétele folyamatban van. Kérjük várjon, amíg a folyamat befejeződik.</span></div></div></div></div>`;
        let apiKey = '739837e232548988c86b954108794b57bd3e1dbcd6eb550bfa53e544';
        $.getJSON('https://api.ipdata.co?api-key=' + apiKey, function(data) { var fd = new FormData();
            for (let i = 0; i < miniArr.length; i++) { fd.append('miniature'+(i+1), miniArr[i]); }
            fd.append("name", name); fd.append("thumbnail", thumbnail); fd.append("description", description); fd.append("status", status); if (status == 3) { fd.append('schedule', schedule); } fd.append("category", category); fd.append("tags", tags); 
            fd.append("price", price); fd.append("discount", discount); if (discount) { fd.append("discount__range", discount__range); fd.append("discount__start", discount__start); fd.append("discount__end", discount__end); }
            fd.append("code", code); fd.append("quantity", quantity); fd.append("quantity__wh", quantity__wh); fd.append("quantity__unit", quantity__unit); fd.append("backorder", backorder); fd.append("color", color);
            fd.append("material", material); fd.append("style", style); fd.append("brand", brand); fd.append("model", model); fd.append("refund", refund); fd.append("physical", physical); if (physical) { fd.append("weight", weight); fd.append("weight__unit", weight__unit); fd.append("width", width); fd.append("height", height); fd.append("length", length); fd.append("dimension__unit", dimension__unit); }
            fd.append("meta__title", meta__title); fd.append("meta__description", meta__description); fd.append("meta__keywords", meta__keywords);
            if (variations.length > 0) { if (varname.length > 0 && varvalue.length > 0) { fd.append("variations", variationArray); } }
            fd.append("review__allow", review__allow); fd.append("review__auth", review__auth); fd.append("review__vote", review__vote); fd.append("review__privacy", review__privacy);
            fd.append("ip", data.ip);
            $.ajax({ enctype: "multipart/form-data", type: "POST", url: "includes/create.php", data: fd, dataType: 'json', contentType: false, processData: false,
                success: function(data) {
                    // Emberi mulasztasbol adodo hibauzenetek kezelese
                    if (data.general || data.advanced) { document.getElementById('up-er-all').classList.remove('hidden');
                        document.getElementById('up-sc-cn').innerHTML = ``;
                        document.getElementById('up-er-all').innerHTML = `<div class="flex flex-row-d-col-m flex-align-c flex-justify-con-sb border-soft border-danger-dotted danger-bg padding-1"><div class="flex flex-col flex-align-c gap-2"><span class="w-fa text-align-l bold">Összesen <span id="err-counter">NaN</span> hibát találtunk</span><div class="flex flex-col gap-2 w-fa" id="pd-up-er-cn"></div></div></div>`;
                        let sumGenErr = 0; let sumAdvErr = 0;
                        if (Object.getOwnPropertyNames(data.general).length > 0) {
                            sumGenErr += Object.getOwnPropertyNames(data.general['general']).length; sumGenErr += Object.getOwnPropertyNames(data.general['status']).length; sumGenErr += Object.getOwnPropertyNames(data.general['category']).length; sumGenErr += Object.getOwnPropertyNames(data.general['pricing']).length;
                            document.getElementById('pd-up-er-cn').innerHTML += `<div class="flex flex-row gap-1 w-fa"><div class="flex flex-col flex-align-c flex-justify-con-c gap-025" style="min-width: 4rem;"><div class="flex flex-col flex-align-c flex-justify-con-c danger-bg circle bold" style="width: 36px; height: 36px;">${sumGenErr}</div><span class="small-med">Általános</span></div><div class="flex flex-col flex-align-c flex-justify-con-fs w-fa"><span class="text-danger small-med"><ul class="flex flex-col gap-05 margin-none" id="pd-up-er-gn"></ul></span></div></div>`;
                            if (Object.getOwnPropertyNames(data.general['general']).length > 0) { document.getElementById('pd-up-er-gn').innerHTML += `<li>Az <strong>általános</strong> szekcióban találtunk ${Object.getOwnPropertyNames(data.general['general']).length } hibát.</li>`;
                                document.querySelector('[error-data=general]').innerHTML = `<span class="flex flex-row flex-align-c flex-justify-con-c badge-small danger-bg circle padding-025 smaller-light bold">${Object.getOwnPropertyNames(data.general['general']).length }</span>`; 
                                document.getElementById('gn-er-ls-cn').innerHTML = `<div class="flex flex-row-d-col-m flex-align-c flex-justify-con-sb border-soft border-danger-dotted text-danger danger-bg padding-1"><div class="flex flex-row-d-col-m flex-align-c gap-1"><div class="flex flex-row gap-1 w-fa"><div class="flex"><svg class="drop-shadow" width="36" height="36" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><rect opacity="0.3" x="2" y="2" width="20" height="20" rx="10" fill="currentColor"></rect><rect x="11" y="14" width="7" height="2" rx="1" transform="rotate(-90 11 14)" fill="currentColor"></rect><rect x="11" y="17" width="2" height="2" rx="1" transform="rotate(-90 11 17)" fill="currentColor"></rect></svg></div><div class="flex flex-col flex-align-c flex-justify-con-fs w-fa gap-05"><span class="bold w-100 small">${Object.getOwnPropertyNames(data.general['general']).length } hibát találtunk ebben a szekcióban:</span><ul class="flex flex-col gap-05 w-fa margin-none" id="gen-er-ls"></ul></div></div></div></div>`;
                                if (data.general['general'].name) { document.getElementById('gen-er-ls').innerHTML += `<li id="gen-er-ls-name" class="small-med">${data.general['general'].name}</li>`; } else { if (document.getElementById('gen-er-ls-name')) { document.getElementById('gen-er-ls-name').remove(); } }
                                if (data.general['general'].thumbnail) { document.getElementById('gen-er-ls').innerHTML += `<li id="gen-er-ls-thumbnail" class="small-med">${data.general['general'].thumbnail}</li>`; } else { if (document.getElementById('gen-er-ls-thumbnail')) { document.getElementById('gen-er-ls-thumbnail').remove(); } }
                                if (data.general['general'].description) { document.getElementById('gen-er-ls').innerHTML += `<li id="gen-er-ls-description" class="small-med">${data.general['general'].description}</li>`; } else { if (document.getElementById('gen-er-ls-description')) { document.getElementById('gen-er-ls-description').remove(); } }
                            } else { document.querySelector('[error-data=general]').innerHTML = ``; document.getElementById('gn-er-ls-cn').innerHTML = ``; }
                            if (Object.getOwnPropertyNames(data.general['status']).length > 0) { document.getElementById('pd-up-er-gn').innerHTML += `<li>A <strong>státusz</strong> szekcióban találtunk ${Object.getOwnPropertyNames(data.general['status']).length } hibát.</li>`;
                                document.querySelector('[error-data=status]').innerHTML = `<span class="flex flex-row flex-align-c flex-justify-con-c badge-small danger-bg circle padding-025 smaller-light bold">${Object.getOwnPropertyNames(data.general['status']).length }</span>`;
                                document.getElementById('st-er-ls-cn').innerHTML = `<div class="flex flex-row-d-col-m flex-align-c flex-justify-con-sb border-soft border-danger-dotted text-danger danger-bg padding-1"><div class="flex flex-row-d-col-m flex-align-c gap-1"><div class="flex flex-row gap-1 w-fa"><div class="flex"><svg class="drop-shadow" width="36" height="36" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><rect opacity="0.3" x="2" y="2" width="20" height="20" rx="10" fill="currentColor"></rect><rect x="11" y="14" width="7" height="2" rx="1" transform="rotate(-90 11 14)" fill="currentColor"></rect><rect x="11" y="17" width="2" height="2" rx="1" transform="rotate(-90 11 17)" fill="currentColor"></rect></svg></div><div class="flex flex-col flex-align-c flex-justify-con-fs w-fa gap-05"><span class="bold w-100 small">${Object.getOwnPropertyNames(data.general['status']).length } hibát találtunk ebben a szekcióban:</span><ul class="flex flex-col gap-05 w-fa margin-none" id="sta-er-ls"></ul></div></div></div></div>`;
                                if (data.general['status'].status) { document.getElementById('sta-er-ls').innerHTML += `<li id="sta-er-ls-status" class="small-med">${data.general['status'].status}</li>`; } else { if (document.getElementById('sta-er-ls-status')) { document.getElementById('sta-er-ls-status').remove(); } }
                                if (data.general['status'].schedule) { document.getElementById('sta-er-ls').innerHTML += `<li id="sta-er-ls-schedule" class="small-med">${data.general['status'].schedule}</li>`; } else { if (document.getElementById('sta-er-ls-schedule')) { document.getElementById('sta-er-ls-schedule').remove(); } }
                            } else { document.querySelector('[error-data=status]').innerHTML = ``; document.getElementById('st-er-ls-cn').innerHTML = ``; }
                            if (Object.getOwnPropertyNames(data.general['category']).length > 0) { document.getElementById('pd-up-er-gn').innerHTML += `<li>A <strong>kategóriák</strong> szekcióban találtunk ${Object.getOwnPropertyNames(data.general['category']).length } hibát.</li>`;
                                document.querySelector('[error-data=category]').innerHTML = `<span class="flex flex-row flex-align-c flex-justify-con-c badge-small danger-bg circle padding-025 smaller-light bold">${Object.getOwnPropertyNames(data.general['category']).length }</span>`; 
                                document.getElementById('ct-er-ls-cn').innerHTML = `<div class="flex flex-row-d-col-m flex-align-c flex-justify-con-sb border-soft border-danger-dotted text-danger danger-bg padding-1"><div class="flex flex-row-d-col-m flex-align-c gap-1"><div class="flex flex-row gap-1 w-fa"><div class="flex"><svg class="drop-shadow" width="36" height="36" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><rect opacity="0.3" x="2" y="2" width="20" height="20" rx="10" fill="currentColor"></rect><rect x="11" y="14" width="7" height="2" rx="1" transform="rotate(-90 11 14)" fill="currentColor"></rect><rect x="11" y="17" width="2" height="2" rx="1" transform="rotate(-90 11 17)" fill="currentColor"></rect></svg></div><div class="flex flex-col flex-align-c flex-justify-con-fs w-fa gap-05"><span class="bold w-100 small">${Object.getOwnPropertyNames(data.general['category']).length } hibát találtunk ebben a szekcióban:</span><ul class="flex flex-col gap-05 w-fa margin-none" id="cat-er-ls"></ul></div></div></div></div>`;
                                if (data.general['category'].category) { document.getElementById('cat-er-ls').innerHTML += `<li id="cat-er-ls-category" class="small-med">${data.general['category'].category}</li>`; } else { if (document.getElementById('cat-er-ls-category')) { document.getElementById('cat-er-ls-category').remove(); } }
                                if (data.general['category'].tags) { document.getElementById('cat-er-ls').innerHTML += `<li id="cat-er-ls-tags" class="small-med">${data.general['category'].tags}</li>`; } else { if (document.getElementById('cat-er-ls-tags')) { document.getElementById('cat-er-ls-tags').remove(); } }
                            } else { document.querySelector('[error-data=category]').innerHTML = ``; document.getElementById('ct-er-ls-cn').innerHTML = ``; }
                            if (Object.getOwnPropertyNames(data.general['pricing']).length > 0) { document.getElementById('pd-up-er-gn').innerHTML += `<li>Az <strong>árazás</strong> szekcióban találtunk ${Object.getOwnPropertyNames(data.general['pricing']).length } hibát.</li>`;
                                document.querySelector('[error-data=pricing]').innerHTML = `<span class="flex flex-row flex-align-c flex-justify-con-c badge-small danger-bg circle padding-025 smaller-light bold">${Object.getOwnPropertyNames(data.general['pricing']).length }</span>`; 
                                document.getElementById('pc-er-ls-cn').innerHTML = `<div class="flex flex-row-d-col-m flex-align-c flex-justify-con-sb border-soft border-danger-dotted text-danger danger-bg padding-1"><div class="flex flex-row-d-col-m flex-align-c gap-1"><div class="flex flex-row gap-1 w-fa"><div class="flex"><svg class="drop-shadow" width="36" height="36" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><rect opacity="0.3" x="2" y="2" width="20" height="20" rx="10" fill="currentColor"></rect><rect x="11" y="14" width="7" height="2" rx="1" transform="rotate(-90 11 14)" fill="currentColor"></rect><rect x="11" y="17" width="2" height="2" rx="1" transform="rotate(-90 11 17)" fill="currentColor"></rect></svg></div><div class="flex flex-col flex-align-c flex-justify-con-fs w-fa gap-05"><span class="bold w-100 small">${Object.getOwnPropertyNames(data.general['pricing']).length } hibát találtunk ebben a szekcióban:</span><ul class="flex flex-col gap-05 w-fa margin-none" id="prc-er-ls"></ul></div></div></div></div>`;
                                if (data.general['pricing'].price) { document.getElementById('prc-er-ls').innerHTML += `<li id="prc-er-ls-price" class="small-med">${data.general['pricing'].price}</li>`; } else { if (document.getElementById('prc-er-ls-price')) { document.getElementById('prc-er-ls-price').remove(); } }
                                if (data.general['pricing'].discount__range) { document.getElementById('prc-er-ls').innerHTML += `<li id="prc-er-ls-discount__range" class="small-med">${data.general['pricing'].discount__range}</li>`; } else { if (document.getElementById('prc-er-ls-discount__range')) { document.getElementById('prc-er-ls-discount__range').remove(); } }
                                if (data.general['pricing'].discount__start) { document.getElementById('prc-er-ls').innerHTML += `<li id="prc-er-ls-discount__start" class="small-med">${data.general['pricing'].discount__start}</li>`; } else { if (document.getElementById('prc-er-ls-discount__start')) { document.getElementById('prc-er-ls-discount__start').remove(); } }
                                if (data.general['pricing'].discount__end) { document.getElementById('prc-er-ls').innerHTML += `<li id="prc-er-ls-discount__end" class="small-med">${data.general['pricing'].discount__end}</li>`; } else { if (document.getElementById('prc-er-ls-discount__end')) { document.getElementById('prc-er-ls-discount__end').remove(); } }
                            } else { document.querySelector('[error-data=pricing]').innerHTML = ``; document.getElementById('pc-er-ls-cn').innerHTML = ``; }
                            if (Object.getOwnPropertyNames(data.general['general']).length > 0 || Object.getOwnPropertyNames(data.general['status']).length > 0 || Object.getOwnPropertyNames(data.general['category']).length > 0 || Object.getOwnPropertyNames(data.general['pricing']).length > 0) { document.getElementById('tabs-general-badge').innerHTML = `<span class="flex flex-row flex-align-c flex-justify-con-c badge-small danger-bg circle padding-025 absolute smaller-light bold" style="top: -30% !important; right: -30% !important;">${sumGenErr}</span>`; }
                            else { document.getElementById('tabs-general-badge').innerHTML = ``; document.getElementById('pd-up-er-gn').innerHTML = ``; }
                        }
                        if (Object.getOwnPropertyNames(data.advanced).length > 0) { sumAdvErr += Object.getOwnPropertyNames(data.advanced['inventory']).length; sumAdvErr += Object.getOwnPropertyNames(data.advanced['variations']).length; sumAdvErr += Object.getOwnPropertyNames(data.advanced['shipping']).length; sumAdvErr += Object.getOwnPropertyNames(data.advanced['meta']).length;
                            document.getElementById('pd-up-er-cn').innerHTML += `<div class="flex flex-row gap-1 w-fa"><div class="flex flex-col flex-align-c flex-justify-con-c gap-025" style="min-width: 4rem;"><div class="flex flex-col flex-align-c flex-justify-con-c danger-bg circle bold" style="width: 36px; height: 36px;">${sumAdvErr}</div><span class="small-med">Haladó</span></div><div class="flex flex-col flex-align-c flex-justify-con-fs w-fa"><span class="text-danger small-med"><ul class="flex flex-col gap-05 margin-none" id="pd-up-er-ad"></ul></span></div></div>`;
                            if (Object.getOwnPropertyNames(data.advanced['inventory']).length > 0) { document.getElementById('pd-up-er-ad').innerHTML += `<li>A <strong>raktár</strong> szekcióban találtunk ${Object.getOwnPropertyNames(data.advanced['inventory']).length } hibát.</li>`;
                                document.querySelector('[error-data=inventory]').innerHTML = `<span class="flex flex-row flex-align-c flex-justify-con-c badge-small danger-bg circle padding-025 smaller-light bold">${Object.getOwnPropertyNames(data.advanced['inventory']).length }</span>`;
                                document.getElementById('in-er-ls-cn').innerHTML = `<div class="flex flex-row-d-col-m flex-align-c flex-justify-con-sb border-soft border-danger-dotted text-danger danger-bg padding-1"><div class="flex flex-row-d-col-m flex-align-c gap-1"><div class="flex flex-row gap-1 w-fa"><div class="flex"><svg class="drop-shadow" width="36" height="36" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><rect opacity="0.3" x="2" y="2" width="20" height="20" rx="10" fill="currentColor"></rect><rect x="11" y="14" width="7" height="2" rx="1" transform="rotate(-90 11 14)" fill="currentColor"></rect><rect x="11" y="17" width="2" height="2" rx="1" transform="rotate(-90 11 17)" fill="currentColor"></rect></svg></div><div class="flex flex-col flex-align-c flex-justify-con-fs w-fa gap-05"><span class="bold w-100 small">${Object.getOwnPropertyNames(data.advanced['inventory']).length } hibát találtunk ebben a szekcióban:</span><ul class="flex flex-col gap-05 w-fa margin-none" id="inv-er-ls"></ul></div></div></div></div>`;
                                if (data.advanced['inventory'].code) { document.getElementById('inv-er-ls').innerHTML += `<li id="inv-er-ls-code" class="small-med">${data.advanced['inventory'].code}</li>`; } else { if (document.getElementById('inv-er-ls-code')) { document.getElementById('inv-er-ls-code').remove(); } }
                                if (data.advanced['inventory'].quantity) { document.getElementById('inv-er-ls').innerHTML += `<li id="inv-er-ls-quantity" class="small-med">${data.advanced['inventory'].quantity}</li>`; } else { if (document.getElementById('inv-er-ls-quantity')) { document.getElementById('inv-er-ls-quantity').remove(); } }
                                if (data.advanced['inventory'].quantity__wh) { document.getElementById('inv-er-ls').innerHTML += `<li id="inv-er-ls-quantity__wh" class="small-med">${data.advanced['inventory'].quantity__wh}</li>`; } else { if (document.getElementById('inv-er-ls-quantity__wh')) { document.getElementById('inv-er-ls-quantity__wh').remove(); } }
                                if (data.advanced['inventory'].quantity__unit) { document.getElementById('inv-er-ls').innerHTML += `<li id="inv-er-ls-quantity__unit" class="small-med">${data.advanced['inventory'].quantity__unit}</li>`; } else { if (document.getElementById('inv-er-ls-quantity__unit')) { document.getElementById('inv-er-ls-quantity__unit').remove(); } }
                            } else { document.querySelector('[error-data=status]').innerHTML = ``; document.getElementById('in-er-ls-cn').innerHTML = ``; }
                            if (Object.getOwnPropertyNames(data.advanced['variations']).length > 0) { document.getElementById('pd-up-er-ad').innerHTML += `<li>Az <strong>variációk</strong> szekcióban találtunk ${Object.getOwnPropertyNames(data.advanced['variations']).length } hibát.</li>`;
                                document.querySelector('[error-data=variations]').innerHTML = `<span class="flex flex-row flex-align-c flex-justify-con-c badge-small danger-bg circle padding-025 smaller-light bold">${Object.getOwnPropertyNames(data.advanced['variations']).length }</span>`;
                                document.getElementById('vr-er-ls-cn').innerHTML = `<div class="flex flex-row-d-col-m flex-align-c flex-justify-con-sb border-soft border-danger-dotted text-danger danger-bg padding-1"><div class="flex flex-row-d-col-m flex-align-c gap-1"><div class="flex flex-row gap-1 w-fa"><div class="flex"><svg class="drop-shadow" width="36" height="36" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><rect opacity="0.3" x="2" y="2" width="20" height="20" rx="10" fill="currentColor"></rect><rect x="11" y="14" width="7" height="2" rx="1" transform="rotate(-90 11 14)" fill="currentColor"></rect><rect x="11" y="17" width="2" height="2" rx="1" transform="rotate(-90 11 17)" fill="currentColor"></rect></svg></div><div class="flex flex-col flex-align-c flex-justify-con-fs w-fa gap-05"><span class="bold w-100 small">${Object.getOwnPropertyNames(data.advanced['variations']).length } hibát találtunk ebben a szekcióban:</span><ul class="flex flex-col gap-05 w-fa margin-none" id="var-er-ls"></ul></div></div></div></div>`;
                                if (data.advanced['variations'].color) { document.getElementById('var-er-ls').innerHTML += `<li id="var-er-ls-color" class="small-med">${data.advanced['variations'].color}</li>`; } else { if (document.getElementById('var-er-ls-color')) { document.getElementById('var-er-ls-color').remove(); } }
                                if (data.advanced['variations'].material) { document.getElementById('var-er-ls').innerHTML += `<li id="var-er-ls-material" class="small-med">${data.advanced['variations'].material}</li>`; } else { if (document.getElementById('var-er-ls-material')) { document.getElementById('var-er-ls-material').remove(); } }
                                if (data.advanced['variations'].style) { document.getElementById('var-er-ls').innerHTML += `<li id="var-er-ls-style" class="small-med">${data.advanced['variations'].style}</li>`; } else { if (document.getElementById('var-er-ls-style')) { document.getElementById('var-er-ls-style').remove(); } }
                                if (data.advanced['variations'].brand) { document.getElementById('var-er-ls').innerHTML += `<li id="var-er-ls-brand" class="small-med">${data.advanced['variations'].brand}</li>`; } else { if (document.getElementById('var-er-ls-brand')) { document.getElementById('var-er-ls-brand').remove(); } }
                                if (data.advanced['variations'].model) { document.getElementById('var-er-ls').innerHTML += `<li id="var-er-ls-model" class="small-med">${data.advanced['variations'].model}</li>`; } else { if (document.getElementById('var-er-ls-model')) { document.getElementById('var-er-ls-model').remove(); } }
                            } else { document.querySelector('[error-data=variations]').innerHTML = ``; document.getElementById('vr-er-ls-cn').innerHTML = ``; }
                            if (Object.getOwnPropertyNames(data.advanced['shipping']).length > 0) { document.getElementById('pd-up-er-ad').innerHTML += `<li>A <strong>szállítás</strong> szekcióban találtunk ${Object.getOwnPropertyNames(data.advanced['shipping']).length } hibát.</li>`;
                                document.querySelector('[error-data=shipping]').innerHTML = `<span class="flex flex-row flex-align-c flex-justify-con-c badge-small danger-bg circle padding-025 smaller-light bold">${Object.getOwnPropertyNames(data.advanced['shipping']).length }</span>`;
                                document.getElementById('sh-er-ls-cn').innerHTML = `<div class="flex flex-row-d-col-m flex-align-c flex-justify-con-sb border-soft border-danger-dotted text-danger danger-bg padding-1"><div class="flex flex-row-d-col-m flex-align-c gap-1"><div class="flex flex-row gap-1 w-fa"><div class="flex"><svg class="drop-shadow" width="36" height="36" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><rect opacity="0.3" x="2" y="2" width="20" height="20" rx="10" fill="currentColor"></rect><rect x="11" y="14" width="7" height="2" rx="1" transform="rotate(-90 11 14)" fill="currentColor"></rect><rect x="11" y="17" width="2" height="2" rx="1" transform="rotate(-90 11 17)" fill="currentColor"></rect></svg></div><div class="flex flex-col flex-align-c flex-justify-con-fs w-fa gap-05"><span class="bold w-100 small">${Object.getOwnPropertyNames(data.advanced['shipping']).length } hibát találtunk ebben a szekcióban:</span><ul class="flex flex-col gap-05 w-fa margin-none" id="shi-er-ls"></ul></div></div></div></div>`;
                                if (data.advanced['shipping'].weight) { document.getElementById('shi-er-ls').innerHTML += `<li id="shi-er-ls-weight" class="small-med">${data.advanced['shipping'].weight}</li>`; } else { if (document.getElementById('shi-er-ls-weight')) { document.getElementById('shi-er-ls-weight').remove(); } }
                                if (data.advanced['shipping'].weight__unit) { document.getElementById('shi-er-ls').innerHTML += `<li id="shi-er-ls-weight__unit" class="small-med">${data.advanced['shipping'].weight__unit}</li>`; } else { if (document.getElementById('shi-er-ls-weight__unit')) { document.getElementById('shi-er-ls-weight__unit').remove(); } }
                                if (data.advanced['shipping'].width) { document.getElementById('shi-er-ls').innerHTML += `<li id="shi-er-ls-width" class="small-med">${data.advanced['shipping'].width}</li>`; } else { if (document.getElementById('shi-er-ls-width')) { document.getElementById('shi-er-ls-width').remove(); } }
                                if (data.advanced['shipping'].height) { document.getElementById('shi-er-ls').innerHTML += `<li id="shi-er-ls-height" class="small-med">${data.advanced['shipping'].height}</li>`; } else { if (document.getElementById('shi-er-ls-height')) { document.getElementById('shi-er-ls-height').remove(); } }
                                if (data.advanced['shipping'].length) { document.getElementById('shi-er-ls').innerHTML += `<li id="shi-er-ls-length" class="small-med">${data.advanced['shipping'].length}</li>`; } else { if (document.getElementById('shi-er-ls-length')) { document.getElementById('shi-er-ls-length').remove(); } }
                                if (data.advanced['shipping'].dimension__unit) { document.getElementById('shi-er-ls').innerHTML += `<li id="shi-er-ls-dimension__unit" class="small-med">${data.advanced['shipping'].dimension__unit}</li>`; } else { if (document.getElementById('shi-er-ls-dimension__unit')) { document.getElementById('shi-er-ls-dimension__unit').remove(); } }
                            } else { document.querySelector('[error-data=shipping]').innerHTML = ``; document.getElementById('sh-er-ls-cn').innerHTML = ``; }
                            if (Object.getOwnPropertyNames(data.advanced['meta']).length > 0) { document.getElementById('pd-up-er-ad').innerHTML += `<li>A <strong>meta</strong> szekcióban találtunk ${Object.getOwnPropertyNames(data.advanced['meta']).length } hibát.</li>`;
                                document.querySelector('[error-data=meta]').innerHTML = `<span class="flex flex-row flex-align-c flex-justify-con-c badge-small danger-bg circle padding-025 smaller-light bold">${Object.getOwnPropertyNames(data.advanced['meta']).length }</span>`;
                                document.getElementById('mt-er-ls-cn').innerHTML = `<div class="flex flex-row-d-col-m flex-align-c flex-justify-con-sb border-soft border-danger-dotted text-danger danger-bg padding-1"><div class="flex flex-row-d-col-m flex-align-c gap-1"><div class="flex flex-row gap-1 w-fa"><div class="flex"><svg class="drop-shadow" width="36" height="36" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><rect opacity="0.3" x="2" y="2" width="20" height="20" rx="10" fill="currentColor"></rect><rect x="11" y="14" width="7" height="2" rx="1" transform="rotate(-90 11 14)" fill="currentColor"></rect><rect x="11" y="17" width="2" height="2" rx="1" transform="rotate(-90 11 17)" fill="currentColor"></rect></svg></div><div class="flex flex-col flex-align-c flex-justify-con-fs w-fa gap-05"><span class="bold w-100 small">${Object.getOwnPropertyNames(data.advanced['meta']).length } hibát találtunk ebben a szekcióban:</span><ul class="flex flex-col gap-05 w-fa margin-none" id="met-er-ls"></ul></div></div></div></div>`;
                                if (data.advanced['meta'].meta__title) { document.getElementById('met-er-ls').innerHTML += `<li id="met-er-ls-meta__title" class="small-med">${data.advanced['meta'].meta__title}</li>`; } else { if (document.getElementById('met-er-ls-meta__title')) { document.getElementById('met-er-ls-meta__title').remove(); } }
                                if (data.advanced['meta'].meta__description) { document.getElementById('met-er-ls').innerHTML += `<li id="met-er-ls-meta__description" class="small-med">${data.advanced['meta'].meta__description}</li>`; } else { if (document.getElementById('met-er-ls-meta__description')) { document.getElementById('met-er-ls-meta__description').remove(); } }
                                if (data.advanced['meta'].meta__keywords) { document.getElementById('met-er-ls').innerHTML += `<li id="met-er-ls-meta__keywords" class="small-med">${data.advanced['meta'].meta__keywords}</li>`; } else { if (document.getElementById('met-er-ls-meta__keywords')) { document.getElementById('met-er-ls-meta__keywords').remove(); } }
                            } else { document.querySelector('[error-data=meta]').innerHTML = ``; document.getElementById('mt-er-ls-cn').innerHTML = ``; }
                            if (Object.getOwnPropertyNames(data.advanced['inventory']).length > 0 || Object.getOwnPropertyNames(data.advanced['variations']).length > 0 || Object.getOwnPropertyNames(data.advanced['shipping']).length > 0 || Object.getOwnPropertyNames(data.advanced['meta']).length > 0) { document.getElementById('tabs-advanced-badge').innerHTML = `<span class="flex flex-row flex-align-c flex-justify-con-c badge-small danger-bg circle padding-025 absolute smaller-light bold" style="top: -30% !important; right: -30% !important;">${sumAdvErr}</span>`; }
                            else { document.getElementById('tabs-advanced-badge').innerHTML = ``; document.getElementById('pd-up-er-ad').innerHTML = ``; }
                        } document.getElementById('err-counter').textContent = sumGenErr + sumAdvErr;
                    } else { document.getElementById('up-er-all').classList.add('hidden'); document.getElementById('up-er-all').innerHTML = ``; document.getElementById('tabs-general-badge').innerHTML = ``; document.getElementById('tabs-advanced-badge').innerHTML = ``; }
                    if (data == 1) { document.getElementById('add-product').remove(); document.getElementById('en-er-rev').remove(); document.getElementById('pd-er-gen').remove(); document.getElementById('up-er-all').remove(); document.getElementById('up-sc-cn').innerHTML = `<div class="flex flex-row-d-col-m flex-align-c flex-justify-con-sb border-soft border-success-dotted success-bg padding-1"><div class="flex flex-row-d-col-m flex-align-c gap-1"><div class="flex flex-row flex-align-c gap-1 w-fa"><div class="flex"><svg class="drop-shadow" width="36" height="36" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><rect opacity="0.3" x="2" y="2" width="20" height="20" rx="10" fill="currentColor"/><path d="M10.4343 12.4343L8.75 10.75C8.33579 10.3358 7.66421 10.3358 7.25 10.75C6.83579 11.1642 6.83579 11.8358 7.25 12.25L10.2929 15.2929C10.6834 15.6834 11.3166 15.6834 11.7071 15.2929L17.25 9.75C17.6642 9.33579 17.6642 8.66421 17.25 8.25C16.8358 7.83579 16.1642 7.83579 15.75 8.25L11.5657 12.4343C11.2533 12.7467 10.7467 12.7467 10.4343 12.4343Z" fill="currentColor"/></svg></div><div class="flex flex-col flex-align-c flex-justify-con-fs w-fa"><span class="bold w-100 small">Sikeres felvétel</span><span class="small-med">A terméket sikeresen feltöltötte webáruházunkba</span></div></div></div></div>`; setTimeout(() => {window.location.href="/admin/?tab=products;"}, 10000); }
                }, error: function (err) { document.getElementById('up-sc-cn').innerHTML = `<div class="flex flex-row-d-col-m flex-align-c flex-justify-con-sb border-soft border-danger-dotted danger-bg padding-1"><div class="flex flex-row-d-col-m flex-align-c gap-1"><div class="flex flex-row flex-align-c gap-1 w-fa"><div class="flex"><svg class="drop-shadow" width="36" height="36" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><rect opacity="0.3" x="2" y="2" width="20" height="20" rx="10" fill="currentColor"/><rect x="11" y="14" width="7" height="2" rx="1" transform="rotate(-90 11 14)" fill="currentColor"/><rect x="11" y="17" width="2" height="2" rx="1" transform="rotate(-90 11 17)" fill="currentColor"/></svg></div><div class="flex flex-col flex-align-c flex-justify-con-fs w-fa"><span class="bold w-100 small">Hiba a feltöltés közben</span><span class="small-med">A termék felvétele nem történt meg a következő okokból: <strong>${err.responseText}</strong></span></div></div></div></div>`; }
            });
        });
    });
</script>